version: '3.8'
services:
    chillax:
        container_name: chillax
        hostname: chillax
        image: directus/directus:11.6.0
        ports:
            - 8055:8055
        volumes:
            - ./uploads:/directus/uploads
            # If you want to load extensions from the host
            - ./extensions:/directus/extensions
        # Environment variables can also be defined in a file (for example `.env`):
        env_file:
            - chillax.env.local
        networks:
            - nginx-network

    chillax-fe:
        container_name: chillax-fe
        hostname: chillax-fe
        build:
            context: ./fe           # Directory containing the Dockerfile (current dir)
            dockerfile: dockerfile
        image: chillax-fe:${FE_VERSION}
        ports: 
            - 3000:3000
        # depends_on:
        #     - chillax
        volumes:
            - ./chillax-fe.env.local:/app/.env.local
        networks:
            - nginx-network
        env_file:
            - ./.env

networks:
    nginx-network:
        name: nginx-network
        external: true
