FROM node:20-alpine
LABEL author="datnn <fsoft.datnn@gmail.com>"

WORKDIR /app

COPY package.json yarn.lock ./
RUN apk add --no-cache git \
    && yarn install  \
    && yarn cache clean

COPY . .
RUN npx update-browserslist-db@latest
RUN yarn add sharp
RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]
